# Generated by Django 4.2.5 on 2023-12-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cars', '0002_owner_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(),
        ),
    ]
