# Generated by Django 4.2.5 on 2023-12-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_cars', '0003_alter_car_engine_alter_car_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
