# Generated by Django 4.1.2 on 2023-12-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_cars', '0003_alter_car_engine_alter_car_type'),
        ('api_cars', '0004_rename_brand_car_brand_id_rename_owner_car_owner_id'),
    ]

    operations = [
    ]
